<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.0.0"
    xmlns:gml="http://www.opengis.net/gml"
    xmlns:ogc="http://www.opengis.net/ogc"
    xmlns="http://www.opengis.net/sld">
    <NamedLayer>
        <Name>gboundaries</Name>
        <UserStyle>
            <Name>gboundaries_style</Name>
            <Title>geoserver style</Title>
            <Abstract>Generated by GeoServer</Abstract>
            <FeatureTypeStyle>
                <Rule>
                    <PolygonSymbolizer>
                        <Fill>
                            <CssParameter name="fill">#00FF00</CssParameter>
                            <CssParameter name="fill-opacity">1</CssParameter>
                        </Fill>
                        <Stroke>
                            <CssParameter name="stroke">#000000</CssParameter>
                            <CssParameter name="stroke-opacity">1</CssParameter>
                        </Stroke>
                    </PolygonSymbolizer>
                    <TextSymbolizer>
                        <Label>
                            <ogc:PropertyName>ADM0NAME</ogc:PropertyName>
                        </Label>
                        
                        <Fill>
                            <CssParameter name="fill">#000000</CssParameter>
                            <CssParameter name="fill-opacity">1</CssParameter>
                        </Fill>
                    </TextSymbolizer>
                </Rule>
            </FeatureTypeStyle>
        </UserStyle>
    </NamedLayer>
</StyledLayerDescriptor>

